name: CI
on:
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: npm-install
        run: npm i

      - name: app-build
        run: npm run build

      - name: app-test
        run: npm run test
